server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lecodedb
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
#  profiles:
#    active: dev

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
