-- MySQL Script generated by MySQL Workbench
-- Wed Jan  3 00:14:33 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lecodedb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `lecodedb` ;

-- -----------------------------------------------------
-- Schema lecodedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lecodedb` DEFAULT CHARACTER SET utf8 ;
USE `lecodedb` ;

-- -----------------------------------------------------
-- Table `lecodedb`.`classroom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lecodedb`.`classroom` ;

CREATE TABLE IF NOT EXISTS `lecodedb`.`classroom` (
  `crid` INT NOT NULL AUTO_INCREMENT,
  `crname` NVARCHAR(10) NOT NULL,
  `crcapacity` TINYINT NULL,
  `crstatus` CHAR(1) NULL,
  `crnote` VARCHAR(45) NULL,
  PRIMARY KEY (`crid`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `crid_UNIQUE` ON `lecodedb`.`classroom` (`crid` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `lecodedb`.`contract`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lecodedb`.`contract` ;

CREATE TABLE IF NOT EXISTS `lecodedb`.`contract` (
  `ctid` INT NOT NULL AUTO_INCREMENT,
  `ctno` VARCHAR(13) NOT NULL,
  `sid` INT NOT NULL,
  `ctamount` DECIMAL NULL,
  `ctstart` DATE NULL,
  `ctend` DATE NULL,
  `ctpaidhour` DECIMAL(3,1) NULL,
  `ctfreehour` DECIMAL(3,1) NULL,
  `classtype` CHAR(1) NULL,
  `ctstatus` CHAR(1) NULL,
  `ctnote` VARCHAR(45) NULL,
  PRIMARY KEY (`ctid`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `cid_UNIQUE` ON `lecodedb`.`contract` (`ctid` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `lecodedb`.`contract_payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lecodedb`.`contract_payment` ;

CREATE TABLE IF NOT EXISTS `lecodedb`.`contract_payment` (
  `cpid` INT NOT NULL AUTO_INCREMENT,
  `ctid` INT NOT NULL,
  `cpdate` DATE NULL,
  `cpamount` DECIMAL NULL,
  `cpphase` TINYINT NULL,
  `cpinstallment` TINYINT NULL,
  `cppayer` VARCHAR(20) NULL,
  `cppayee` VARCHAR(20) NULL,
  `cpchannel` VARCHAR(10) NULL,
  `cpstatus` CHAR(1) NULL,
  `ctnote` VARCHAR(45) NULL,
  PRIMARY KEY (`cpid`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `cid_UNIQUE` ON `lecodedb`.`contract_payment` (`cpid` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `lecodedb`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lecodedb`.`student` ;

CREATE TABLE IF NOT EXISTS `lecodedb`.`student` (
  `sid` INT NOT NULL AUTO_INCREMENT,
  `sno` VARCHAR(10) NOT NULL,
  `sname` NVARCHAR(16) NULL,
  `snick` NVARCHAR(10) NULL,
  `sbirth` DATE NULL,
  `sgender` CHAR(1) NULL,
  `sschool` NVARCHAR(20) NULL,
  `saddress` VARCHAR(45) NULL,
  `sfamily` VARCHAR(10) NULL,
  `sfname` VARCHAR(20) NULL,
  `sfmobile` VARCHAR(15) NULL,
  `ssource` VARCHAR(10) NULL,
  `sstatus` CHAR(1) NULL,
  `snote` VARCHAR(45) NULL,
  PRIMARY KEY (`sid`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `sno_UNIQUE` ON `lecodedb`.`student` (`sno` ASC) VISIBLE;

CREATE UNIQUE INDEX `sid_UNIQUE` ON `lecodedb`.`student` (`sid` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `lecodedb`.`studentours`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lecodedb`.`studentours` ;

CREATE TABLE IF NOT EXISTS `lecodedb`.`studentours` (
  `shguid` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`shguid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lecodedb`.`study_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lecodedb`.`study_group` ;

CREATE TABLE IF NOT EXISTS `lecodedb`.`study_group` (
  `sgid` INT NOT NULL AUTO_INCREMENT,
  `sgno` VARCHAR(6) NULL,
  `sgname` VARCHAR(10) NULL,
  `sgcourse` VARCHAR(10) NULL,
  `sgcapacity` TINYINT NULL,
  `sgstart` DATE NULL,
  `sgend` DATE NULL DEFAULT '9999-12-31',
  `sgclasstime` TIME NULL,
  `sgclasshour` DECIMAL(3,1) NULL DEFAULT 1,
  `crid` INT NULL,
  `sgstatus` CHAR(1) NULL,
  `sgnote` VARCHAR(45) NULL,
  PRIMARY KEY (`sgid`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `sgid_UNIQUE` ON `lecodedb`.`study_group` (`sgid` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `lecodedb`.`teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lecodedb`.`teacher` ;

CREATE TABLE IF NOT EXISTS `lecodedb`.`teacher` (
  `tid` INT NOT NULL AUTO_INCREMENT,
  `tno` VARCHAR(10) NOT NULL,
  `tname` NVARCHAR(36) NULL,
  `tnick` NVARCHAR(36) NULL,
  `tbirth` DATE NULL,
  `tgender` CHAR(1) NULL,
  `tavatar` VARCHAR(45) NULL,
  `tjoindate` DATE NULL,
  `tresigndate` DATE NULL,
  `tstatus` CHAR(1) NULL,
  PRIMARY KEY (`tid`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `tid_UNIQUE` ON `lecodedb`.`teacher` (`tid` ASC) VISIBLE;

CREATE UNIQUE INDEX `tno_UNIQUE` ON `lecodedb`.`teacher` (`tno` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `lecodedb`.`time_record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lecodedb`.`time_record` ;

CREATE TABLE IF NOT EXISTS `lecodedb`.`time_record` (
  `trid` INT NOT NULL AUTO_INCREMENT,
  `ctid` INT NOT NULL,
  `tid` INT NULL,
  `sgid` INT NULL,
  `trhour` DECIMAL(3,1) NULL,
  `trcontent` VARCHAR(20) NULL,
  `trtype` CHAR(3) NULL,
  `trstatus` CHAR(1) NULL,
  `trnote` VARCHAR(45) NULL,
  PRIMARY KEY (`trid`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `trid_UNIQUE` ON `lecodedb`.`time_record` (`trid` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `lecodedb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lecodedb`.`user` ;

CREATE TABLE IF NOT EXISTS `lecodedb`.`user` (
  `uid` INT NOT NULL AUTO_INCREMENT,
  `uno` VARCHAR(10) NOT NULL,
  `uuser` VARCHAR(36) NULL,
  `uname` NVARCHAR(10) NULL,
  `upassword` CHAR(36) NULL,
  `uwechatid` NVARCHAR(36) NULL,
  `uwechatopenid` CHAR(36) NULL,
  `uphone` VARCHAR(15) NULL,
  `ustatus` CHAR(1) NULL,
  `umemo` VARCHAR(45) NULL,
  PRIMARY KEY (`uid`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `uno_UNIQUE` ON `lecodedb`.`user` (`uno` ASC) VISIBLE;

CREATE UNIQUE INDEX `uid_UNIQUE` ON `lecodedb`.`user` (`uid` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
