-- MySQL Script generated by MySQL Workbench
-- Sat Jan  6 19:31:55 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`student` ;

CREATE TABLE IF NOT EXISTS `mydb`.`student` (
  `sid` INT NOT NULL AUTO_INCREMENT,
  `sno` VARCHAR(10) NOT NULL,
  `sname` VARCHAR(16) NULL,
  `snick` VARCHAR(10) NULL,
  `sbirth` DATE NULL,
  `sgender` CHAR(1) NULL,
  `sschool` VARCHAR(20) NULL,
  `saddress` VARCHAR(45) NULL,
  `sfamily` VARCHAR(10) NULL,
  `sfname` VARCHAR(20) NULL,
  `sfmobile` VARCHAR(15) NULL,
  `ssource` VARCHAR(10) NULL,
  `sstatus` VARCHAR(3) NULL,
  `snote` VARCHAR(45) NULL,
  PRIMARY KEY (`sid`),
  UNIQUE INDEX `sid_UNIQUE` (`sid` ASC) VISIBLE,
  UNIQUE INDEX `sid_UNIQUE` (`sno` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `uid` INT NOT NULL AUTO_INCREMENT,
  `uno` VARCHAR(10) NOT NULL,
  `uuser` VARCHAR(36) NULL,
  `uname` VARCHAR(10) NULL,
  `upassword` VARCHAR(36) NULL,
  `uwechatid` VARCHAR(36) NULL,
  `uwechatopenid` VARCHAR(36) NULL,
  `uphone` VARCHAR(15) NULL,
  `ustatus` VARCHAR(3) NULL,
  `unote` VARCHAR(45) NULL,
  UNIQUE INDEX `uno_UNIQUE` (`uno` ASC) VISIBLE,
  PRIMARY KEY (`uid`),
  UNIQUE INDEX `uid_UNIQUE` (`uid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`teacher` ;

CREATE TABLE IF NOT EXISTS `mydb`.`teacher` (
  `tid` INT NOT NULL AUTO_INCREMENT,
  `tno` VARCHAR(10) NOT NULL,
  `tname` VARCHAR(36) NULL,
  `tnick` VARCHAR(36) NULL,
  `tbirth` DATE NULL,
  `tgender` CHAR(1) NULL,
  `tavatar` VARCHAR(45) NULL,
  `tjoindate` DATE NULL,
  `tresigndate` DATE NULL,
  `tstatus` VARCHAR(3) NULL,
  `tnote` VARCHAR(45) NULL,
  PRIMARY KEY (`tid`),
  UNIQUE INDEX `tid_UNIQUE` (`tid` ASC) VISIBLE,
  UNIQUE INDEX `tno_UNIQUE` (`tno` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contract`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`contract` ;

CREATE TABLE IF NOT EXISTS `mydb`.`contract` (
  `ctid` INT NOT NULL AUTO_INCREMENT,
  `ctno` VARCHAR(13) NOT NULL,
  `sid` INT NOT NULL,
  `ctamount` DECIMAL NULL,
  `ctstart` DATE NULL,
  `ctend` DATE NULL,
  `ctpaidhour` DECIMAL(3,1) NULL,
  `ctfreehour` DECIMAL(3,1) NULL,
  `classtype` VARCHAR(3) NULL,
  `ctstatus` VARCHAR(3) NULL,
  `ctnote` VARCHAR(45) NULL,
  PRIMARY KEY (`ctid`),
  UNIQUE INDEX `cid_UNIQUE` (`ctid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`studentours`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`studentours` ;

CREATE TABLE IF NOT EXISTS `mydb`.`studentours` (
  `shguid` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`shguid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`classroom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`classroom` ;

CREATE TABLE IF NOT EXISTS `mydb`.`classroom` (
  `crid` INT NOT NULL AUTO_INCREMENT,
  `crname` VARCHAR(10) NOT NULL,
  `crcapacity` TINYINT NULL,
  `crstatus` VARCHAR(1) NULL,
  `crnote` VARCHAR(45) NULL,
  PRIMARY KEY (`crid`),
  UNIQUE INDEX `crid_UNIQUE` (`crid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`study_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`study_group` ;

CREATE TABLE IF NOT EXISTS `mydb`.`study_group` (
  `sgid` INT NOT NULL AUTO_INCREMENT,
  `sgno` VARCHAR(6) NULL,
  `sgname` VARCHAR(10) NULL,
  `sgcourse` VARCHAR(10) NULL,
  `sgcapacity` TINYINT NULL,
  `sgstart` DATE NULL,
  `sgend` DATE NULL DEFAULT '9999-12-31',
  `sgclasstime` TIME NULL,
  `sgclasshour` DECIMAL(3,1) NULL DEFAULT 1,
  `crid` INT NULL,
  `sgstatus` VARCHAR(3) NULL,
  `sgnote` VARCHAR(45) NULL,
  PRIMARY KEY (`sgid`),
  UNIQUE INDEX `sgid_UNIQUE` (`sgid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`time_record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`time_record` ;

CREATE TABLE IF NOT EXISTS `mydb`.`time_record` (
  `trid` INT NOT NULL AUTO_INCREMENT,
  `ctid` INT NOT NULL,
  `tid` INT NULL,
  `sgid` INT NULL,
  `trhour` DECIMAL(3,1) NULL,
  `trcontent` VARCHAR(20) NULL,
  `trtype` VARCHAR(3) NULL,
  `trstatus` VARCHAR(3) NULL,
  `trnote` VARCHAR(45) NULL,
  PRIMARY KEY (`trid`),
  UNIQUE INDEX `trid_UNIQUE` (`trid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contract_payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`contract_payment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`contract_payment` (
  `cpid` INT NOT NULL AUTO_INCREMENT,
  `ctid` INT NOT NULL,
  `cpdate` DATE NULL,
  `cpamount` DECIMAL NULL,
  `cpphase` TINYINT NULL,
  `cpinstallment` TINYINT NULL,
  `cppayer` VARCHAR(20) NULL,
  `cppayee` VARCHAR(20) NULL,
  `cpchannel` VARCHAR(10) NULL,
  `cpstatus` VARCHAR(3) NULL,
  `ctnote` VARCHAR(45) NULL,
  PRIMARY KEY (`cpid`),
  UNIQUE INDEX `cid_UNIQUE` (`cpid` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
